### ISSUE TITLE
支付宝导入我的SDK中报错

### ISSUE THREAD

**Issue by Huangchuanjia** [tsy12321/PayiOS#2]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AlipaySDK", referenced from:
      objc-class-ref in OrangeSDK(SDKClient.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
上面是错误，我要做一个SDK（OrangeSDK）里面要封装微信付，Alipay，applePay第三方支付，我在把支付宝导入进去时，报上面的错误

**Comment by tsy12321** [comment]
可以了么

**Comment by Huangchuanjia** [comment]
没有
